id = "azure"
name = "Azure"
dashboard_url = "https://portal.azure.com"

[[locations]]
path = "%AZURE_CONFIG_DIR%/azureProfile.json"
format = "json"
strategy = "azure_profile"
source_type = "config_file"

[[locations]]
path = "%USERPROFILE%/.azure/azureProfile.json"
format = "json"
strategy = "azure_profile"
source_type = "config_file"

[[env_vars]]
name = "AZURE_CLIENT_ID"
label = "Azure client"

[[env_vars]]
name = "AZURE_TENANT_ID"
label = "Azure tenant"
